In [1]:
1+1

2

In [2]:
import numpy as np

In [3]:
a = np.random.rand(3,5)

In [4]:
a

array([[0.78470826, 0.8842201 , 0.07971765, 0.34916282, 0.47118047],
       [0.69125097, 0.98582819, 0.67742217, 0.44219085, 0.09078037],
       [0.96044898, 0.64625625, 0.19947453, 0.48763739, 0.34309357]])

In [5]:
# reduce sum
b = np.add.reduce(a)

In [6]:
b

array([2.43640821, 2.51630454, 0.95661434, 1.27899105, 0.90505441])

In [7]:
c = np.add.reduce(array = a, axis=1)

In [8]:
c

array([2.56898929, 2.88747256, 2.63691071])

In [9]:
d = np.vstack((a,b))


In [10]:
d

array([[0.78470826, 0.8842201 , 0.07971765, 0.34916282, 0.47118047],
       [0.69125097, 0.98582819, 0.67742217, 0.44219085, 0.09078037],
       [0.96044898, 0.64625625, 0.19947453, 0.48763739, 0.34309357],
       [2.43640821, 2.51630454, 0.95661434, 1.27899105, 0.90505441]])

In [11]:
e = np.hstack((d[:3], c.reshape(3,1)))
e


array([[0.78470826, 0.8842201 , 0.07971765, 0.34916282, 0.47118047,
        2.56898929],
       [0.69125097, 0.98582819, 0.67742217, 0.44219085, 0.09078037,
        2.88747256],
       [0.96044898, 0.64625625, 0.19947453, 0.48763739, 0.34309357,
        2.63691071]])

In [12]:
acc_mul = np.multiply.accumulate(e)
acc_mul

array([[7.84708262e-01, 8.84220096e-01, 7.97176461e-02, 3.49162815e-01,
        4.71180468e-01, 2.56898929e+00],
       [5.42430350e-01, 8.71689100e-01, 5.40025005e-02, 1.54396603e-01,
        4.27739381e-02, 7.41788607e+00],
       [5.20976674e-01, 5.63334531e-01, 1.07721235e-02, 7.52895560e-02,
        1.46754629e-02, 1.95603032e+01]])

In [13]:
b+d #sum with different shapes

array([[3.22111647, 3.40052464, 1.03633199, 1.62815387, 1.37623487],
       [3.12765918, 3.50213274, 1.63403651, 1.72118191, 0.99583478],
       [3.39685719, 3.16256079, 1.15608887, 1.76662844, 1.24814797],
       [4.87281642, 5.03260908, 1.91322869, 2.55798211, 1.81010881]])

In [14]:
b.shape # check shape of b

(5,)

In [15]:
d.shape

(4, 5)

In [16]:
b*d

array([[1.91186965, 2.22496704, 0.07625904, 0.44657612, 0.42644396],
       [1.68416955, 2.48064396, 0.64803176, 0.56555815, 0.08216118],
       [2.34004577, 1.62617754, 0.1908202 , 0.62368385, 0.31051834],
       [5.93608497, 6.33178855, 0.915111  , 1.63581812, 0.81912348]])

In [19]:
b = b[:,np.newaxis]

In [20]:
b+d # should generate dims mismatch error


ValueError: operands could not be broadcast together with shapes (5,1) (4,5) 