In [2]:
1+1

2

In [3]:
import numpy as np

In [4]:
a = np.random.rand(3,5)

In [5]:
a

array([[0.59370572, 0.18743383, 0.43503013, 0.52241933, 0.85613639],
       [0.83360716, 0.27279056, 0.50127839, 0.42160598, 0.60307455],
       [0.28100196, 0.0150687 , 0.91144702, 0.97375906, 0.57687618]])

In [6]:
# reduce sum
b = np.add.reduce(a)

In [7]:
b

array([1.70831484, 0.47529308, 1.84775554, 1.91778437, 2.03608713])

In [8]:
c = np.add.reduce(array = a, axis=1)

In [9]:
c

array([2.5947254 , 2.63235664, 2.75815291])

In [10]:
d = np.vstack((a,b))


In [11]:
d

array([[0.59370572, 0.18743383, 0.43503013, 0.52241933, 0.85613639],
       [0.83360716, 0.27279056, 0.50127839, 0.42160598, 0.60307455],
       [0.28100196, 0.0150687 , 0.91144702, 0.97375906, 0.57687618],
       [1.70831484, 0.47529308, 1.84775554, 1.91778437, 2.03608713]])

In [12]:
e = np.hstack((d[:3], c.reshape(3,1)))
e


array([[0.59370572, 0.18743383, 0.43503013, 0.52241933, 0.85613639,
        2.5947254 ],
       [0.83360716, 0.27279056, 0.50127839, 0.42160598, 0.60307455,
        2.63235664],
       [0.28100196, 0.0150687 , 0.91144702, 0.97375906, 0.57687618,
        2.75815291]])

In [13]:
acc_mul = np.multiply.accumulate(e)
acc_mul

array([[5.93705718e-01, 1.87433829e-01, 4.35030132e-01, 5.22419334e-01,
        8.56136392e-01, 2.59472540e+00],
       [4.94917340e-01, 5.11301786e-02, 2.18071203e-01, 2.20255114e-01,
        5.16314072e-01, 6.83024265e+00],
       [1.39072741e-01, 7.70465155e-04, 1.98760349e-01, 2.14475413e-01,
        2.97849290e-01, 1.88388537e+01]])

In [14]:
b+d #sum with different shapes

array([[2.30202056, 0.66272691, 2.28278567, 2.4402037 , 2.89222352],
       [2.541922  , 0.74808364, 2.34903393, 2.33939035, 2.63916168],
       [1.9893168 , 0.49036178, 2.75920256, 2.89154343, 2.61296331],
       [3.41662968, 0.95058617, 3.69551108, 3.83556874, 4.07217425]])

In [15]:
b.shape # check shape of b

(5,)

In [16]:
d.shape

(4, 5)

In [17]:
b*d

array([[1.01423629, 0.089086  , 0.80382934, 1.00188763, 1.74316829],
       [1.42406349, 0.12965547, 0.92623992, 0.80854936, 1.22791233],
       [0.48003981, 0.00716205, 1.68413128, 1.8674599 , 1.17457017],
       [2.91833959, 0.22590351, 3.41420054, 3.67789689, 4.14565079]])

In [18]:
b[:,np.newaxis]

array([[1.70831484],
       [0.47529308],
       [1.84775554],
       [1.91778437],
       [2.03608713]])

In [ ]:
b+d # shoul