In [26]:
1+1

2

In [27]:
import numpy as np

In [28]:
a = np.random.rand(3,5)

In [29]:
a

array([[0.11008834, 0.38067407, 0.67855196, 0.17971106, 0.86745243],
       [0.94919826, 0.07031005, 0.47848842, 0.32198398, 0.80151228],
       [0.82583261, 0.97544293, 0.91789995, 0.6705151 , 0.96167122]])

In [30]:
# reduce sum
b = np.add.reduce(a)

In [31]:
b

array([1.88511921, 1.42642705, 2.07494033, 1.17221014, 2.63063594])

In [32]:
c = np.add.reduce(array = a, axis=1)

In [33]:
c

array([2.21647787, 2.62149299, 4.35136181])

In [34]:
d = np.vstack((a,b))


In [35]:
d

array([[0.11008834, 0.38067407, 0.67855196, 0.17971106, 0.86745243],
       [0.94919826, 0.07031005, 0.47848842, 0.32198398, 0.80151228],
       [0.82583261, 0.97544293, 0.91789995, 0.6705151 , 0.96167122],
       [1.88511921, 1.42642705, 2.07494033, 1.17221014, 2.63063594]])

In [36]:
e = np.hstack((d[:3], c.reshape(3,1)))
e


array([[0.11008834, 0.38067407, 0.67855196, 0.17971106, 0.86745243,
        2.21647787],
       [0.94919826, 0.07031005, 0.47848842, 0.32198398, 0.80151228,
        2.62149299],
       [0.82583261, 0.97544293, 0.91789995, 0.6705151 , 0.96167122,
        4.35136181]])

In [37]:
acc_mul = np.multiply.accumulate(e)
acc_mul

array([[ 0.11008834,  0.38067407,  0.67855196,  0.17971106,  0.86745243,
         2.21647787],
       [ 0.10449566,  0.02676521,  0.32467926,  0.05786408,  0.69527378,
         5.8104812 ],
       [ 0.08629593,  0.02610794,  0.29802307,  0.03879874,  0.66862479,
        25.28350599]])

In [38]:
b+d #sum with different shapes

array([[1.99520755, 1.80710112, 2.75349229, 1.3519212 , 3.49808837],
       [2.83431746, 1.4967371 , 2.55342875, 1.49419412, 3.43214822],
       [2.71095181, 2.40186998, 2.99284028, 1.84272525, 3.59230716],
       [3.77023841, 2.8528541 , 4.14988067, 2.34442028, 5.26127188]])

In [39]:
b.shape # check shape of b

(5,)

In [40]:
d.shape

(4, 5)

In [41]:
b*d

array([[0.20752965, 0.54300379, 1.40795483, 0.21065913, 2.28195155],
       [1.78935186, 0.10029216, 0.99283493, 0.37743289, 2.10848702],
       [1.55679291, 1.39139818, 1.90458763, 0.7859846 , 2.52980688],
       [3.55367442, 2.03469413, 4.30537739, 1.37407662, 6.92024545]])

In [42]:
b = b[:,np.newaxis]

In [43]:
b+d # should generate dims mismatch error


ValueError: operands could not be broadcast together with shapes (5,1) (4,5) 

In [44]:
# boolean index
b>1.0

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [51]:
b = b.reshape((5))

In [52]:
b

array([1.88511921, 1.42642705, 2.07494033, 1.17221014, 2.63063594])

In [53]:
b>1.0

array([ True,  True,  True,  True,  True])

In [54]:
b>1.5

array([ True, False,  True, False,  True])

In [55]:
ib = b[b>1.5]

In [56]:
ib

array([1.88511921, 2.07494033, 2.63063594])

In [57]:
np.sum(b[b>1.5])

6.5906954784173735

In [59]:
int_arr = np.arange(1,20,2)

In [60]:
int_arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [62]:
int_arr[(int_arr>4) & (int_arr<11)]

array([5, 7, 9])

In [63]:
int_arr.mean()

10.0

In [65]:
(int_arr - int_arr.mean()).mean() # must be 0

0.0