In [1]:
1+1

2

In [6]:
import numpy as np

In [10]:
a = np.random.rand(3,5)

In [11]:
a

array([[0.50172536, 0.68795649, 0.98132375, 0.37810334, 0.42131049],
       [0.79282541, 0.26386815, 0.04045531, 0.24068916, 0.37174711],
       [0.4729242 , 0.21778218, 0.1428758 , 0.64145217, 0.86257391]])

In [12]:
# reduce sum
b = np.add.reduce(a)

In [13]:
b

array([1.76747497, 1.16960682, 1.16465485, 1.26024467, 1.65563151])

In [17]:
c = np.add.reduce(array = a, axis=1)

In [18]:
c

array([2.97041942, 1.70958513, 2.33760826])

In [21]:
d = np.vstack((a,b))


In [22]:
d

array([[0.50172536, 0.68795649, 0.98132375, 0.37810334, 0.42131049],
       [0.79282541, 0.26386815, 0.04045531, 0.24068916, 0.37174711],
       [0.4729242 , 0.21778218, 0.1428758 , 0.64145217, 0.86257391],
       [1.76747497, 1.16960682, 1.16465485, 1.26024467, 1.65563151]])

In [38]:
e = np.hstack((d[:3], c.reshape(3,1)))
e


array([[0.50172536, 0.68795649, 0.98132375, 0.37810334, 0.42131049,
        2.97041942],
       [0.79282541, 0.26386815, 0.04045531, 0.24068916, 0.37174711,
        1.70958513],
       [0.4729242 , 0.21778218, 0.1428758 , 0.64145217, 0.86257391,
        2.33760826]])

In [39]:
acc_mul = np.multiply.accumulate(e)
acc_mul

array([[5.01725361e-01, 6.87956486e-01, 9.81323747e-01, 3.78103337e-01,
        4.21310493e-01, 2.97041942e+00],
       [3.97780614e-01, 1.81529808e-01, 3.96997525e-02, 9.10053729e-02,
        1.56620957e-01, 5.07818489e+00],
       [1.88120079e-01, 3.95339574e-02, 5.67213383e-03, 5.83755942e-02,
        1.35097152e-01, 1.18708070e+01]])