In [26]:
1+1

2

In [3]:
import numpy as np

In [4]:
a = np.random.rand(3,5)

In [5]:
a

array([[0.08767419, 0.29646349, 0.99419299, 0.02116088, 0.54770167],
       [0.73434764, 0.68651053, 0.25273874, 0.67131501, 0.42043452],
       [0.57563651, 0.84237048, 0.80931657, 0.55461316, 0.04524163]])

In [6]:
# reduce sum
b = np.add.reduce(a)

In [7]:
b

array([1.39765834, 1.82534449, 2.0562483 , 1.24708906, 1.01337782])

In [8]:
c = np.add.reduce(array = a, axis=1)

In [9]:
c

array([1.94719323, 2.76534644, 2.82717835])

In [10]:
d = np.vstack((a,b))


In [11]:
d

array([[0.08767419, 0.29646349, 0.99419299, 0.02116088, 0.54770167],
       [0.73434764, 0.68651053, 0.25273874, 0.67131501, 0.42043452],
       [0.57563651, 0.84237048, 0.80931657, 0.55461316, 0.04524163],
       [1.39765834, 1.82534449, 2.0562483 , 1.24708906, 1.01337782]])

In [12]:
e = np.hstack((d[:3], c.reshape(3,1)))
e


array([[0.08767419, 0.29646349, 0.99419299, 0.02116088, 0.54770167,
        1.94719323],
       [0.73434764, 0.68651053, 0.25273874, 0.67131501, 0.42043452,
        2.76534644],
       [0.57563651, 0.84237048, 0.80931657, 0.55461316, 0.04524163,
        2.82717835]])

In [13]:
acc_mul = np.multiply.accumulate(e)
acc_mul

array([[8.76741947e-02, 2.96463487e-01, 9.94192991e-01, 2.11608827e-02,
        5.47701674e-01, 1.94719323e+00],
       [6.43833383e-02, 2.03525305e-01, 2.51271085e-01, 1.42056182e-02,
        2.30272689e-01, 5.38466387e+00],
       [3.70613999e-02, 1.71443709e-01, 2.03357853e-01, 7.87862288e-03,
        1.04179123e-02, 1.52234051e+01]])

In [14]:
b+d #sum with different shapes

array([[1.48533254, 2.12180798, 3.0504413 , 1.26824994, 1.5610795 ],
       [2.13200599, 2.51185502, 2.30898705, 1.91840407, 1.43381234],
       [1.97329485, 2.66771497, 2.86556488, 1.80170222, 1.05861946],
       [2.79531669, 3.65068899, 4.11249661, 2.49417812, 2.02675565]])

In [15]:
b.shape # check shape of b

(5,)

In [16]:
d.shape

(4, 5)

In [17]:
b*d

array([[0.12253857, 0.54114799, 2.04430765, 0.02638951, 0.55502873],
       [1.02636711, 1.25311821, 0.51969361, 0.83718961, 0.42605902],
       [0.80454317, 1.53761632, 1.66415583, 0.69165201, 0.04584687],
       [1.95344885, 3.33188252, 4.22815709, 1.55523112, 1.02693461]])

In [18]:
b = b[:,np.newaxis]

In [19]:
b+d # should generate dims mismatch error


ValueError: operands could not be broadcast together with shapes (5,1) (4,5) 

In [20]:
# boolean index
b>1.0

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [21]:
b = b.reshape((5))

In [22]:
b

array([1.39765834, 1.82534449, 2.0562483 , 1.24708906, 1.01337782])

In [23]:
b>1.0

array([ True,  True,  True,  True,  True])

In [24]:
b>1.5

array([False,  True,  True, False, False])

In [25]:
ib = b[b>1.5]

In [26]:
ib

array([1.82534449, 2.0562483 ])

In [27]:
np.sum(b[b>1.5])

3.8815927990846353

In [28]:
int_arr = np.arange(1,20,2)

In [29]:
int_arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [30]:
int_arr[(int_arr>4) & (int_arr<11)]

array([5, 7, 9])

In [31]:
int_arr.mean()

10.0

In [32]:
(int_arr - int_arr.mean()).mean() # must be 0

0.0

In [55]:
# complex indicies
inds = np.array([[1,2],[1,2]])
int_arr[inds]

array([[3, 5],
       [3, 5]])

In [56]:
inds = np.array([[1,2],[1,2],[5,7]])
int_arr[inds]

array([[ 3,  5],
       [ 3,  5],
       [11, 15]])